spring:
  application:
    name: cliente-microservice

  # db h2 en memoria para prd
  datasource:
    url: jdbc:h2:mem:proddb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

    h2:
      console:
        enabled: true
        path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

# Config
server:
  port: ${PORT:8080}

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# CORS
management:
  endpoints:
    web:
      exposure:
        include: health,info

# Logging
logging:
  level:
    com.pinapp.cliente_microservice: INFO
    root: WARN